# visualize_monaco.jl — Beautiful F1 telemetry visualization

using CSV
using DataFrames
using CairoMakie
using Colors
using Statistics

println("🏎️  VERSTAPPEN MONACO 2024 VISUALIZATION")
println("═" ^ 50)

# Load data
df = CSV.read("monaco_2024_verstappen.csv", DataFrame)

println("\n📊 Data loaded:")
println("   Samples: $(nrow(df))")
println("   Duration: $(round(df.time[end], digits=2))s")
println("   Max speed: $(round(maximum(df.speed_kmh), digits=1)) km/h")

# Create figure with dark theme
set_theme!(
    theme_dark(),
    fontsize = 16,
    linewidth = 2,
    backgroundcolor = :black,
    textcolor = :white
)

fig = Figure(resolution = (1920, 1080), backgroundcolor = "#0a0a0a")

# Title
Label(fig[0, :], 
      "MAX VERSTAPPEN — MONACO 2024 QUALIFYING\nFastest Lap Analysis",
      fontsize = 24,
      color = :white,
      font = :bold)

# Grid layout
ga = fig[1, 1] = GridLayout()
gb = fig[2, 1] = GridLayout()

# ═══════════════════════════════════════════════════════════════
# PLOT 1: Speed trace
# ═══════════════════════════════════════════════════════════════
ax1 = Axis(ga[1, 1],
    xlabel = "Time (s)",
    ylabel = "Speed (km/h)",
    title = "Speed Trace",
    backgroundcolor = "#111111"
)

# Speed line with gradient
lines!(ax1, df.time, df.speed_kmh, 
       color = :cyan, 
       linewidth = 3)

# Braking zones (red highlights)
brake_mask = df.brake .> 0
scatter!(ax1, df.time[brake_mask], df.speed_kmh[brake_mask],
         color = :red,
         markersize = 3,
         alpha = 0.3)

# Max speed annotation
max_idx = argmax(df.speed_kmh)
scatter!(ax1, [df.time[max_idx]], [df.speed_kmh[max_idx]],
         color = :yellow,
         markersize = 12)
text!(ax1, df.time[max_idx], df.speed_kmh[max_idx] + 10,
      text = "$(round(df.speed_kmh[max_idx], digits=1)) km/h",
      color = :yellow,
      fontsize = 14)

ylims!(ax1, 0, 300)

# ═══════════════════════════════════════════════════════════════
# PLOT 2: Throttle vs Brake
# ═══════════════════════════════════════════════════════════════
ax2 = Axis(ga[1, 2],
    xlabel = "Time (s)",
    ylabel = "Input (%)",
    title = "Driver Inputs",
    backgroundcolor = "#111111"
)

# Throttle (green)
band!(ax2, df.time, zeros(length(df.time)), df.throttle,
      color = (:green, 0.5),
      label = "Throttle")

# Brake (red)
brake_pct = df.brake .* 100
band!(ax2, df.time, zeros(length(df.time)), brake_pct,
      color = (:red, 0.5),
      label = "Brake")

axislegend(ax2, position = :rt)
ylims!(ax2, 0, 105)

# ═══════════════════════════════════════════════════════════════
# PLOT 3: Wheel speeds (individual wheels)
# ═══════════════════════════════════════════════════════════════
ax3 = Axis(gb[1, 1],
    xlabel = "Time (s)",
    ylabel = "Wheel Speed (m/s)",
    title = "Individual Wheel Speeds",
    backgroundcolor = "#111111"
)

lines!(ax3, df.time, df.wheel_speed_fl, color = :cyan, label = "FL")
lines!(ax3, df.time, df.wheel_speed_fr, color = :magenta, label = "FR")
lines!(ax3, df.time, df.wheel_speed_rl, color = :yellow, label = "RL")
lines!(ax3, df.time, df.wheel_speed_rr, color = :orange, label = "RR")

axislegend(ax3, position = :lt)

# ═══════════════════════════════════════════════════════════════
# PLOT 4: Speed heatmap (time vs speed gradient)
# ═══════════════════════════════════════════════════════════════
ax4 = Axis(gb[1, 2],
    xlabel = "Time (s)",
    ylabel = "Speed (km/h)",
    title = "Speed Heatmap",
    backgroundcolor = "#111111"
)

# Create 2D density
n_bins = 100
time_edges = range(minimum(df.time), maximum(df.time), length=n_bins)
speed_edges = range(0, 300, length=n_bins)

# Create heatmap data
heatmap_data = zeros(n_bins-1, n_bins-1)
for i in 1:nrow(df)
    t_idx = searchsortedfirst(time_edges, df.time[i]) - 1
    s_idx = searchsortedfirst(speed_edges, df.speed_kmh[i]) - 1
    if 1 <= t_idx < n_bins && 1 <= s_idx < n_bins
        heatmap_data[s_idx, t_idx] += 1
    end
end

hm = heatmap!(ax4, 
              time_edges[1:end-1],
              speed_edges[1:end-1],
              heatmap_data,
              colormap = :turbo,
              colorrange = (0, maximum(heatmap_data)))

Colorbar(gb[1, 3], hm, label = "Density")

# ═══════════════════════════════════════════════════════════════
# Footer stats
# ═══════════════════════════════════════════════════════════════
lap_time = round(df.time[end], digits=2)
avg_speed = round(mean(df.speed_kmh), digits=1)
max_speed = round(maximum(df.speed_kmh), digits=1)
max_throttle = round(maximum(df.throttle), digits=1)

footer = "Lap time: $(lap_time)s | Avg: $(avg_speed) km/h | Max: $(max_speed) km/h | Peak throttle: $(max_throttle)%"
Label(fig[3, :], footer,
      fontsize = 14,
      color = :gray,
      halign = :center)

# Add watermark
Label(fig[4, :],
      "Generated by APEX Telemetry Stack | github.com/Chikimonki/project-apex",
      fontsize = 12,
      color = :gray,
      halign = :right)

# Save figure
output_file = "verstappen_monaco_2024.png"
save(output_file, fig, px_per_unit = 2)

println("\n✅ Visualization saved: $output_file")
println("\nOpening image...")

# Display figure
display(fig)

println("\n🏁 Visualization complete!")
